fragment testOption on TestOption {
  id
  name
}

fragment testRelayConnection on TestRelayConnection {
  edges {
    cursor
    node {
      id
    }
  }
  pageInfo {
    hasPreviousPage
    hasNextPage
    startCursor
    endCursor
  }
}

fragment testUnion on TestUnion {
  ... on TestUnionOne {
    id
    oneName
  }
  ... on TestUnionTwo {
    id
    twoName
  }
}

query TestObject($id: ID!) {
  testObject(id: $id) {
    id
    size
    sizeNonNull
    belongsToField {
      id
      name
    }
    belongsToNonNullField {
      id
      name
    }
    hasManyField {
      ...testOption
    }
    hasManyFilteredField(name: "Foo") {
      ...testOption
    }
    hasManyNonNullField {
      ...testOption
    }
    hasManyNestedNonNullField {
      ...testOption
    }
    interfaceField {
      ... on TestImplOne {
        id
        label
      }
    }
    interfaceNonNullField {
      ... on TestImplOne {
        id
        label
      }
    }
    interfaceNestedNonNullField {
      ... on TestInterface {
        id
        label
      }
      ... on TestImplOne {
        description
      }
    }
    relayConnectionField(first: 1, after: "VGVzdFJlbGF5Tm9kZTox") {
      ...testRelayConnection
    }
    relayConnectionFilteredField(first: 1, color: "blue") {
      edges {
        cursor
        node {
          id
          color
        }
      }
      pageInfo {
        hasPreviousPage
        hasNextPage
        startCursor
        endCursor
      }
    }
    relayConnectionNonNullField(last: 1, before: "VGVzdFJlbGF5Tm9kZToz") {
      ...testRelayConnection
    }
    unionField {
      ...testUnion
    }
    unionNonNullField(oneName: "foo") {
      ...testUnion
    }
    unionNestedNonNullField(twoName: "bar") {
      ...testUnion
    }
    unionSingularField {
      ...testUnion
    }
  }
}
